### PR TITLE
Get code generation and most API tests working

### PR DESCRIPTION
**Pull request by dano**
This addresses issue #1, and additionally gets all but three of the API tests working. The failing tests can't be fixed without either a Py4J enhancement (see https://github.com/bartdag/py4j/issues/163), or a Java shim between the Python code and the Vert.x Java API.

There are a few other pieces here that are probably worth calling out:

1) Java sets are being translated to Python sets, which requires that any list/map inside the set to be be converted to a `frozenset`/`frozendict` (I've added the`frozendict` type to `vertx_python.util`). It also requires some customized JSON decoding/encoding. It seems to be working, but it would simplify things significantly to just translate a Java set to a Python list.

2) Currently, JUnit just executes a single unit test, which triggers all 121+ Python unit tests (using the Python `unittest` module). If any of those fail, the single JUnit test reports failure. I do it this way because the performance of having a unique JUnit test for every Python unit test is atrocious, due to the high overhead of launching a Python process and launching/shutting down the Java GatewayServer/GatewayClient.

3) Because we need to use the Py4J callback server, it's necessary to be very careful about how the Python script is shut down. `vertx_python.util.vertx_shutdown()` _must_ be called prior to the main thread exiting, or the program will hang due to the callback server continuing to run in a background thread. I've added a `handle_vertx_shutdown()` context manager to help with this.

4) There's no attempt at `asyncio` integration here - everything is callback based. I do have another branch where I've demonstrated how `asyncio` integration can be done - and I'm working through getting all the unit tests working there. It sounds like the preference is to have that eventually become a completely separate repo, perhaps sharing some common code with this one?

5) The generated code should be compatible with Python 2.7 and Python 3.x. At some point we may want to add a Python3 specific verticle, which would use "python3" rather than "python" to launch the Python script.

### CODE REVIEW

**Comment by kuujo** [comment]
Awesome!

I think @purplefox and others should weigh in on the asyncio topic. For context on what you're weighing in on: what we currently have is more or less a direct port of the feel of the API as it was in Vert.x 2. But truthfully, Python's syntax can make for some rather unreadable async code, so there's interest in using a more concise API with coroutines to clean up code. The Python API can be extended to add this support, so I view this as similar to the extension of the Java API to add RxJava Observables. So, while I think it is desirable and will be well received, I suggested we might want the asyncio integration a separate project, but it shouldn't be my decision.

**Comment by kuujo** [comment]
Actually maybe this discussion should be in the dev group

**Comment by dano** [comment]
One thing I've been wondering about on the Java end here - the Py4J GatewayServer works by listening for connections in a background thread, and then additionally spawning a thread for each client connection. That means that all the Vert.x API calls coming in from the Python side aren't being executed in the Vert.x event loop thread. This seems like it might be unsafe to me. Is it ok for all the operations to be executed in the same, non-event loop thread?

**Comment by kuujo** [comment]
Hmm... That's a valid concern. 

What is the relationship between a verticle instance (an instance of a Python script) and a connection? Is that one-to-one?

Much of the Vert.x API is thread safe, but that may not always be the case. If an event arrives on a Py4J thread and makes a direct call to a Vert.x API, what we can do in cases where that's an issue is wrap the Vert.x API to execute calls on the correct Context. In that case, rather than calling Vert.x methods directly, we'd be calling a Java wrapper which internally does context.runOnContext(...), and that would behave as if it were called from a Java verticle and should be done for any API that's not thread safe. I suppose alternatively we could dig through the Py4J code and see if we can wrap it to handle the Vert.x Context in all cases.

I'll dig in the Java code and will start a discussion regarding this and the asyncio issue on the dev group.

**Comment by dano** [comment]
@kuujo Yes, the relationship is always 1-1; the Python script opens a single connection to the GatewayServer, and maintains that for its entire lifetime. I suspect that using `runOnContext` in a Java shim is the best way to handle this (there's two usecases for that now - along with handling type casting Py4J can't deal with), unless we want to ship a modified version of Py4J.

I'll keep an eye out for the threads on vertx-dev (and also make sure I sign up for the mailing list :)).

**Comment by dano** [comment]
@kuujo I ended up adding the shim needed to get the last of the unit tests working myself. Let me know if anything else needs to be done prior to merging this work, which just adds callback-based APIs. We can handle the coroutine-style question separately.

**Pull request closed without merging**
